#!/usr/bin/env bash
# Build the academic-format bWAPP audit report.
# Renders front matter (roman page numbers) and body (arabic, restarting at 1) as two
# separate PDFs via WeasyPrint, then merges them. Also emits a DOCX via LibreOffice.
# WeasyPrint is used (not Chrome) because it renders table borders uniformly and
# handles tables that span page breaks correctly.
set -euo pipefail
cd "$(dirname "$0")"

SRC="2305551076_Ravi Arnan Irianto.html"
OUT="2305551076_Ravi Arnan Irianto.pdf"
VENV="/tmp/wp-venv"
WP="$VENV/bin/weasyprint"
TMP="$(mktemp -d)"

# Ensure WeasyPrint is available (isolated venv; system python is PEP 668 managed).
if [ ! -x "$WP" ]; then
  echo "Setting up WeasyPrint venv at $VENV ..."
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet weasyprint
fi

# Split master HTML at the SPLIT marker into front.html and body.html.
python3 - "$SRC" "$TMP" <<'PY'
import sys, pathlib
src = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
tmp = pathlib.Path(sys.argv[2])
marker = "<!-- ===SPLIT=== body starts here -->"
head = src[:src.index("</head>")+len("</head>")]
pre, post = src.split(marker, 1)
front = pre.rstrip() + "\n</body>\n</html>\n"      # cover + daftar (roman)
body  = head + "\n<body>\n" + post                 # chapters (arabic, restarts at 1)
(tmp / "front.html").write_text(front, encoding="utf-8")
(tmp / "body.html").write_text(body, encoding="utf-8")
print("split ok")
PY

# Logo is referenced relatively; make it reachable next to the temp HTML.
ln -sf "$PWD/unud_logo.png" "$TMP/unud_logo.png"

"$WP" "$TMP/front.html" "$TMP/front.pdf"
"$WP" "$TMP/body.html"  "$TMP/body.pdf"

pdfunite "$TMP/front.pdf" "$TMP/body.pdf" "$OUT"
echo "merged -> $OUT ($(pdfinfo "$OUT" | awk '/^Pages/{print $2}') pages)"

# Keep fragments for TOC page-number verification.
cp "$TMP/body.pdf" "./_body_preview.pdf"
cp "$TMP/front.pdf" "./_front_preview.pdf"

# DOCX (editable copy) via LibreOffice. Auto-TOC field is not generated by this path.
libreoffice --headless --convert-to docx --outdir . "$SRC" >/dev/null 2>&1 || \
  libreoffice --headless --infilter='HTML (StarWriter)' --convert-to docx --outdir . "$SRC" >/dev/null 2>&1
echo "docx -> ${SRC%.html}.docx"

rm -rf "$TMP"
